### ISSUE TITLE
[typo] Can't find the image

### ISSUE THREAD

**Issue by zhiqwang** [openmlsys/openmlsys-zh#103]
> 接下来我们通过 [图5.2.9 ](https://openmlsys.github.io/chapter_frontend_and_ir/intermediate_representation.html#mindir-example)中的一段程序作为示例，来进一步分析MindIR。

此图5.2.9 没有正确找到路径: https://openmlsys.github.io/chapter_frontend_and_ir/intermediate_representation.html#mindir-example

可能是因为路径后缀的大小写问题导致的 https://github.com/openmlsys/openmlsys.github.io/blob/main/docs/_images/中间表示-MindIR示例.PNG

cc @LiangZhibo

**Comment by eedalong** [comment]
Great！

**Comment by LiangZhibo** [comment]
已解决。
