### ISSUE TITLE
提议：希望有大佬可以增加部分内容

### ISSUE THREAD

**Issue by zhurou603** [openmlsys/openmlsys-zh#105]
<img width="1273" alt="image" src="https://user-images.githubusercontent.com/32234672/158958029-89eb8e17-5f31-41f9-8a50-7a5c4085805c.png">
例如这部分对于数据流的操作只是简单罗列了shuffle、组batch、prefetch。但在分布式环境下如何实现以及具体工程上怎么跟run graph的计算部分overlap起来？

**Comment by zhurou603** [comment]
似乎IO这一块有很多可以扩展的内容

**Comment by hanjr92** [comment]
感谢关注哈，第三章中介绍各种操作只是为了简单介绍计算图构成，数据流、分布式后续都有单独的章节进行详细的介绍。

**Comment by eedalong** [comment]
@zhurou603  这部分在数据处理框架有介绍～

**Comment by zhurou603** [comment]
> @zhurou603 这部分在数据处理框架有介绍～

感谢.
