### ISSUE TITLE
图1.3.1 机器学习系统基本组成 所示内容对应章节和目录不符

### ISSUE THREAD

**Issue by worldzhang1996** [openmlsys/openmlsys-zh#108]
(1) 章节/位置：1.3章机器学习系统基本组成最上方

(2) 问题描述: 图中所示内容章节和目录对不上。比如：计算加速器（第4章）位于目录的第7章；数据处理（第7章）位于目录第8章等等。
 
(3)建议: 调整图片内容。

**Comment by eedalong** [comment]
非常感谢！
