### ISSUE TITLE
拓展篇希望补充章节

### ISSUE THREAD

**Issue by zhurou603** [openmlsys/openmlsys-zh#110]
拓展篇如果有大佬能供多补充一些开源的项目那就更好了，比如深度推荐系统中nv的hugeCTR之类的，联邦学习中字节的框架。如果有大佬能够分析开源项目中的一些具体设计实现那就更棒了！

**Comment by future-xy** [comment]
感谢建议，NVIDIA Merlin系列在加了

**Comment by ganzhiliang** [comment]
@chengtianwu  考虑下这个建议

**Comment by chengtianwu** [comment]
> @chengtianwu 考虑下这个建议

> 

好的，我添加下字节还有其他公司的联邦学习框架

**Comment by zhurou603** [comment]
深度学习推荐系统的开源实现除了Merlin还有其他好的参考吗？大佬们
