### ISSUE TITLE
10.2.3. 模型并行 算子内并行图片错误

### ISSUE THREAD

**Issue by tingshua-yts** [openmlsys/openmlsys-zh#119]
![image](https://user-images.githubusercontent.com/57979478/159103006-b4a8125b-2158-46b6-bfb0-189594089750.png)

图10.2.3 并没有体现出设备1和设备2，也没有体现出算子1和算子2

**Comment by Laicheng0830** [comment]
@tingshua-yts 感谢指出，图片上传错误，今天将会修复
