### ISSUE TITLE
第六章多了空格

### ISSUE THREAD

**Issue by HermosaHUI** [openmlsys/openmlsys-zh#126]
![image](https://user-images.githubusercontent.com/38346033/159112297-db763f07-b5a4-4e8a-bd92-4ca1422f8fa0.png)

**Comment by HermosaHUI** [comment]
![image](https://user-images.githubusercontent.com/38346033/159112628-002ddb0b-d865-4741-ae5c-ba5b323a816d.png)
语句有问题，多了“使用”

**Comment by eedalong** [comment]
应该改成 -------> 并且后续计算过程中无需再次使用该算子的输出的情况下

> ![image](https://user-images.githubusercontent.com/38346033/159112628-002ddb0b-d865-4741-ae5c-ba5b323a816d.png) 语句有问题，多了“使用”

**Comment by eedalong** [comment]
> ![image](https://user-images.githubusercontent.com/38346033/159112297-db763f07-b5a4-4e8a-bd92-4ca1422f8fa0.png)

这个也需要查一下 @yuanzhigang-source

**Comment by yuanzhigang-source** [comment]
我来提交Pr解决这个问题

**Comment by yuanzhigang-source** [comment]
@eedalong

**Comment by eedalong** [comment]
Great!
