### ISSUE TITLE
7.3章 图缺失

### ISSUE THREAD

**Issue by HermosaHUI** [openmlsys/openmlsys-zh#131]
![image](https://user-images.githubusercontent.com/38346033/159114644-aa623556-840d-4473-9e4a-7898f6e860e1.png)
 该图缺失。

**Comment by anyrenwei** [comment]
感谢

> ![image](https://user-images.githubusercontent.com/38346033/159114644-aa623556-840d-4473-9e4a-7898f6e860e1.png) 该图缺失。

感谢提醒，之前这个图打算重绘来着。我会尽快补上

**Comment by anyrenwei** [comment]
图已更新，相关pr为https://github.com/openmlsys/openmlsys-zh/pull/165。issue先关闭了
