### ISSUE TITLE
整体段落不太规整

### ISSUE THREAD

**Issue by yuanzhigang-source** [openmlsys/openmlsys-zh#133]
![image](https://user-images.githubusercontent.com/83761884/159114997-5e6732d0-e53e-4f08-96bd-04c59bf470b9.png)
有的会多出一些空格，有的因为引用或其他原因导致不齐整

**Comment by eedalong** [comment]
这个应该是网页渲染的问题，有的时候可能就是某个单词放不下，被换行了
