### ISSUE TITLE
错别字

### ISSUE THREAD

**Issue by WangHuiNEU** [openmlsys/openmlsys-zh#147]
<img src="https://gitee.com/wanghui88888888/picture/raw/master/img/image-20220320122004620.png" alt="image-20220320122004620" style="zoom:67%;" />

应该是~100GB

**Comment by WangHuiNEU** [comment]
<img src="https://gitee.com/wanghui88888888/picture/raw/master/img/image-20220320122232175.png" alt="image-20220320122232175" style="zoom:67%;" />
这句话表述有问题，应该说是：“对于使用更大规模的模型... ...”

**Comment by WangHuiNEU** [comment]
<img src="https://gitee.com/wanghui88888888/picture/raw/master/img/image-20220320123019690.png" alt="image-20220320123019690" style="zoom:67%;" />

这句话没搞太懂，这个“先用”是不是改为“先前”更好

**Comment by eedalong** [comment]
确实是这样

**Comment by yuanzhigang-source** [comment]
我来提交pr解决这个问题 @eedalong
