### ISSUE TITLE
10.5.4 参数服务器的表示是否可以商讨下？

### ISSUE THREAD

**Issue by twoflypig** [openmlsys/openmlsys-zh#151]
原文的表述中
```text
接下来，我们介绍另一种常见的分布式训练系统实现：参数服务器。TensorFlow原生提供了参数服务器的实现。而其他框架，例如PyTorch和MindSpore，则需要用户使用第三方的参数服务器实现，例如PS-Lite。
```

现在Pytorch已经可以使用RPC接口实现自己的PS版本，可以见这个链接：https://pytorch.org/tutorials/intermediate/rpc_param_server_tutorial.html

MindSpore也提供了PS的内置实现：https://www.mindspore.cn/docs/programming_guide/zh-CN/r1.6/apply_parameter_server_training.html

**Comment by eedalong** [comment]
有道理，只不过Pytorch这个应该是提供了rpc的能力，构建PS本身还是要用户来做的吧 @twoflypig

**Comment by twoflypig** [comment]
看文档是的~

**Comment by eedalong** [comment]
是的，我理解这里应该指的是那种完善的工业可用的Parameter Server功能，应该描述上没啥问题。具体可以看下 @luomai 老师的回答

**Comment by cailun01** [comment]
措辞可以再斟酌一下。比如改为：

**Comment by eedalong** [comment]
> 措辞可以再斟酌一下。比如改为： 而其他框架，例如PyTorch和MindSpore，或需要用户使用框架提供的rpc接口实现，例如`torch.distributed.rpc`，或依赖第三方的参数服务器实现，例如PS-Lite。

@luomai  麦老师看下~

**Comment by luomai** [comment]
可以的。@cailun01 @twoflypig 你们愿意提交PR修改吗？我也可以自己提交一个PR。

**Comment by cailun01** [comment]
@eedalong 请看下这个pr
https://github.com/openmlsys/openmlsys-zh/pull/194
