### ISSUE TITLE
5.4 关于类型系统和静态分析的两个问题

### ISSUE THREAD

**Issue by hungrymegumin** [openmlsys/openmlsys-zh#152]
1. 文中提到 `Python语言是一门动态弱类型的语言`，我对这里有一点疑惑，因为根据能查到的一些资料来看，认为Python是动态强类型的观点似乎更占据主流。

2. 静态分析概述这里似乎是照搬的百度百科，但是静态分析更多的理解应该是基于IR的，所以lexer，parser，sema这些我认为不应该算作静态分析之内，在南大李樾谭添老师的静态分析课程中，也是这么认为的。https://spa-book.pblo.gq/ch1/2intermediaterepresentation

**Comment by eedalong** [comment]
非常好的讨论！ @LiangZhibo 麻烦回答一下该问题～

**Comment by LiangZhibo** [comment]
@hungrymegumin 非常感谢你提出的问题。
1. 主流观点上python确实为强类型语言， 不支持大部分类型的隐式转换。 我会将这点修改体现在接下来的PR中。
2. 本章节的概述部分确实将语法解析以及静态分析分开， 大体上来说，语法解析用来从高级语言向AST再向中间表示的转换，静态分析是直接作用于语法解析得到的IR， 将该IR变为静态强类型的IR， 用以后续的优化以及自动微分等流程。 因此我同意你的观点， 静态分析确实不应该包括语法解析阶段。 我将再接下来的PR中修改这一点，并且着重于介绍一下为什么需要静态解析，而不是泛泛的介绍其概念。但本章节属于是了解章节， 所以不会过于细节的展开说明。
再次感谢你对社区的贡献～ 欢迎继续讨论！
