### ISSUE TITLE
PDF链接似乎无法访问

### ISSUE THREAD

**Issue by eedalong** [openmlsys/openmlsys-zh#161]
@Laicheng0830

**Comment by Laicheng0830** [comment]
我放在我们实验室的服务器了，其他人无法访问吗？改成百度网盘?

**Comment by eedalong** [comment]
你们实验室那肯定有访问限制吧，百度网盘我觉得暂时没啥问题，好几个社区用户都要求PDF了，所以我觉得救急一下可以的。

**Comment by Whisht** [comment]
直接传到github上也可以吧？

**Comment by Laicheng0830** [comment]
> 直接传到github上也可以吧？

可以是可以，就是文件比较大可能会导致clone项目困难

**Comment by Whisht** [comment]
> 可以是可以，就是文件比较大可能会导致clone项目困难

哦，那这样话还是放外链比较好，百度网盘的话可能会有链接失效的问题。

**Comment by Laicheng0830** [comment]
> > 可以是可以，就是文件比较大可能会导致clone项目困难
> 
> 哦，那这样话还是放外链比较好，百度网盘的话可能会有链接失效的问题。
谢谢提醒，后续会完善好
