### ISSUE TITLE
10.1 空格问题

### ISSUE THREAD

**Issue by HermosaHUI** [openmlsys/openmlsys-zh#184]
![image](https://user-images.githubusercontent.com/38346033/159481132-ce1e7fa0-fceb-47bd-8c8b-bef499954644.png)

**Comment by luomai** [comment]
hello啦。谢谢哈。这些问题，你可以合并成一个issue。

**Comment by HermosaHUI** [comment]
![MTmJwZ9bwJ](https://user-images.githubusercontent.com/38346033/159483389-15a5bd09-9ace-4b97-940e-9abfcaee29c8.png)
多余空格问题

**Comment by HermosaHUI** [comment]
![image](https://user-images.githubusercontent.com/38346033/159486241-efa07da4-5571-49c4-800f-56b769b28d1c.png)
 图掩盖了文字。

**Comment by luomai** [comment]
@future-xy 你正好在改这个图。一起改了文字的空格吧。
