### ISSUE TITLE
10.1.3 有错别字

### ISSUE THREAD

**Issue by HermosaHUI** [openmlsys/openmlsys-zh#186]
![image](https://user-images.githubusercontent.com/38346033/159481907-38e6ed19-dd4b-497a-b57e-f875ff25d22e.png)
起 -> 其

**Comment by luomai** [comment]
第十章的issue请合并。

**Comment by luomai** [comment]
@HermosaHUI

**Comment by HermosaHUI** [comment]
> @HermosaHUI

ok, done, please go to : https://github.com/openmlsys/openmlsys-zh/issues/184
