### ISSUE TITLE
10.2.1 多余空格

### ISSUE THREAD

**Issue by HermosaHUI** [openmlsys/openmlsys-zh#187]
![image](https://user-images.githubusercontent.com/38346033/159483018-242be15a-5498-401c-b4db-1851a34c6664.png)

**Comment by 13218011661** [comment]
您获得了我们书籍检视的奖励，麻烦在5月15日前，在此贴回复一下邮箱哦

**Comment by HermosaHUI** [comment]
> 您获得了我们书籍检视的奖励，麻烦在5月15日前，在此贴回复一下邮箱哦

13611044380@163.com  刚看到。
