### ISSUE TITLE
2.3章节存在笔误，池化后应为32 * 16 * 16

### ISSUE THREAD

**Issue by wangch1009** [openmlsys/openmlsys-zh#188]
https://github.com/openmlsys/openmlsys-zh/blob/cd2e6a1538e9dc38cc79eddb5a2da0024691e579/chapter_programming_interface/neural_network_layer.md?plain=1#L50

**Comment by Laicheng0830** [comment]
@wangch1009 感谢！我将修改好

**Comment by eedalong** [comment]
@wangch1009  BTW, 我们的Readme里面有网页版链接的，可以直接读网页版，不用读md文件

**Comment by eedalong** [comment]
@Laicheng0830 看来咱的网页版还是不够醒目，让志鹏他们找设计设计一下好了 @Rudysheeppig

**Comment by wangch1009** [comment]
> @wangch1009 BTW, 我们的Readme里面有网页版链接的，可以直接读网页版，不用读md文件

我是读的网页版的，昨天github有点问题，截图贴不了，因此直接找md文件提issue了。
