### ISSUE TITLE
第3.2节的recurrent_control函数似乎有错

### ISSUE THREAD

**Issue by Ywandung-Lyou** [openmlsys/openmlsys-zh#202]
[@hanjr92](https://github.com/hanjr92)
```python
def recurrent_control(X, W, cur_num = 3):
    for i in range(cur_num):
        Y = matmul(X, W)
    return Y
```
这段代码似乎有错，这么写`Y`等于`matmul(X, W)`，没有循环3次。这么改才对吧：
```python
def recurrent_control(X, W, cur_num = 3):
    for i in range(cur_num):
        X = matmul(X, W)
    return X
```

**Comment by hanjr92** [comment]
感谢指出，写的时候一直在考虑循环展开和图片 = =！

**Comment by Ywandung-Lyou** [comment]
相应的，把W声明成序列，每次用索引获取W1、W2更好。不搭配图我都没读懂代码。

def recurrent_control(X, W, cur_num = 3):

    for i in range(cur_num):

        Y = matmul(X, W)

    return Y

#利用展开机制将上述代码展开，可得到等价表示

def recurrent_control(X, W, cur_num = 3):

    X1 = matmul(X, W)

    X2 = matmul(X1, W1)

    Y = matmul(X2, W2)

    return Y
***@***.***
　　祝好
Ywandung Lyou


________________________________
发件人: Ywandung Lyou ***@***.***>
发送时间: Thursday, March 24, 2022 2:36:29 PM
收件人: openmlsys/openmlsys-zh ***@***.***>
抄送: Ywandung Lyou ***@***.***>; Your activity ***@***.***>
主题: [openmlsys/openmlsys-zh] 第3.2节的recurrent_control函数似乎有错 (Issue #202)


@hanjr92<https://github.com/hanjr92>

def recurrent_control(X, W, cur_num = 3):

    for i in range(cur_num):

        Y = matmul(X, W)

    return Y

这段代码似乎有错，这么写Y等于matmul(X, W)，没有循环3次。这么改才对吧：

def recurrent_control(X, W, cur_num = 3):

    for i in range(cur_num):

        X = matmul(X, W)

    return X

―

**Comment by hanjr92** [comment]
感谢感谢！
