### ISSUE TITLE
错别字或语句错误勘误

### ISSUE THREAD

**Issue by WangHuiNEU** [openmlsys/openmlsys-zh#209]
<img src="https://gitee.com/wanghui88888888/picture/raw/master/img/image-20220325103514599.png" alt="image-20220325103514599" style="zoom:80%;" />

首先分枝结构错误，应该是分支结构。程序只有三种结构：顺序、循环和分支。第二点语句说法不通顺，建议改为：这些模型拓扑复杂（例如说，分支结构，带有条件的if-else循环)，并且复杂的.......

**Comment by hanjr92** [comment]
感谢，已经重新调整描述了！
