### ISSUE TITLE
DRAFT 部分语法逻辑存在优化空间

### ISSUE THREAD

**Issue by zwpaper** [openmlsys/openmlsys-zh#223]
1. 语法错误 https://openmlsys.github.io/chapter_introduction/requirements_for_machine_learning_systems.html
    > 人们需要使用各种优化方法（例如Mini-Batch SGD和其变种）来迭代计算梯度，最终模型的性能达到令开发者满意的状态（该过程称为训练）

   应该是 人们需要使用各种优化方法（例如Mini-Batch SGD和其变种）来迭代计算梯度，`使`最终模型的性能达到令开发者满意的状态（该过程称为训练）
2. 和 `1.` 同一个位置，后面推理提供了`（Inference）` 的英文参考，前面是否也应该加上对应的 `（Training）`参考
   > 为了让机器学习模型达到最佳的性能，人们需要使用各种优化方法（例如Mini-Batch SGD和其变种）来迭代计算梯度，最终模型的性能达到令开发者满意的状态（该过程称为训练）。同时，根据应用的要求，训练好的模型也需要部署到各种计算设备中，以提供模型推理服务（Inference）

**Comment by luomai** [comment]
谢谢，我来处理。
