### ISSUE TITLE
有关标点、缺漏字等typo的汇总

### ISSUE THREAD

**Issue by xlinsist** [openmlsys/openmlsys-zh#224]
以下指出了8个问题并给出具体描述和修改建议。这些问题都是“标点”、“缺漏字”等有关句子表达规范的typo。

3.1. 计算图的设计背景和作用

问题1：标点格式不规范。
描述：“对于输入数据，算子和算子执行顺序的统一表达。”、“这个数据结构可以准确表述用户的输入数据，模型所带有的多个算子，以及算子之间的执行顺序。”这两句中的逗号“，”应该都改为顿号“、”
修改建议：对于以上两句，分别改为：“对于输入数据、算子和算子执行顺序的统一表达。” 以及 “这个数据结构可以准确表述用户的输入数据、模型所带有的多个算子、以及算子之间的执行顺序。”

问题2：标点格式不规范。
描述：“（例如说，分支结构，带有条件的if-else循环)”，这里的右括号采用的是英文格式的右括号，与其中文歌是的左括号不一致。
修改建议：将右括号改为中文格式的右括号。即“（例如说，分支结构，带有条件的if-else循环）”

3.2. 计算图的基本构成

问题3：文本中存在多余空格。
描述：表3.2.1中“表示存储的数 据类型”里面“数”和“据”中间多了个空格。
修改建议：把空格删掉。

3.3. 计算图的生成

问题4：文本中存在多余空格。
描述：表3.3.2中“pa ddle.jit.to_static()”和“padd le.jit.TracedLayer.trace()”里面的“paddle”单词均多了个空格。
修改建议：把空格删掉。

问题5：句子不通顺。
描述：“每执行一句立即进行运算并会返回具体的值，”
修改建议：改为：“每执行一句就会立即进行运算并会返回具体的值”

5.6. 总结

问题6：标点格式不规范。
描述：“自动微分的实现方法大体上可以划分为基本表达式法，操作符重载法以及代码变化法。”这里的逗号应该改为顿号。
修改建议：改为：“自动微分的实现方法大体上可以划分为基本表达式法、操作符重载法以及代码变化法。”

7.4. 总结

问题7：句子缺漏字。
描述：“越底层的编程方式越能够灵活地制加速器”，“制”附近缺字，原意应该为“控制”
修改建议：改为：“越底层的编程方式越能够灵活地控制加速器”

9.3.1.2 训练时量化

问题8：标点格式不规范
描述：“全量化不仅会量化模型的权重，还会量化模型的激活值，在模型推理时执行量化算子来加快模型的推理速度、”这一句中，最后的顿号属于是打错标点了。
修改建议：将顿号改为句号。

以上。
个人邮箱：xlinsist12138@gmail.com

**Comment by xlinsist** [comment]
我可以直接提pr来修正吗

**Comment by eedalong** [comment]
可以的，非常欢迎
