### ISSUE TITLE
[拓展章节] 机器人学习系统

### ISSUE THREAD

**Issue by Jiankai-Sun** [openmlsys/openmlsys-zh#236]
本章打算包含以下内容

![image](https://user-images.githubusercontent.com/25477396/161352678-42e90089-3708-4eb0-a4b8-896e466ce6bc.png)

欢迎大家提建议~

**Comment by eedalong** [comment]
机器人学习系统有没有一个什么定义之类的，感觉这个章节里面涵盖的面比较宽

**Comment by hanjr92** [comment]
感觉还是挺难对这个下定义的，如果按照地面、空中这样分类，现在水面水下其实也挺火的哈，那这章内容可太丰富，感觉作者工作量太大了。

**Comment by eedalong** [comment]
我觉得雨露均沾没啥问题，起码我作为一个外行，看了这个大纲，对这个领域有新知识的摄入。我觉得可以先propose一个概述文字出来，这样就知道下文的一些逻辑了～

**Comment by hanjr92** [comment]
雨露均沾对读者友好啊：），读者可以快速接触更广泛的知识面，期待一下这一章。

**Comment by eedalong** [comment]
确实

**Comment by Jiankai-Sun** [comment]
> 感觉还是挺难对这个下定义的，如果按照地面、空中这样分类，现在水面水下其实也挺火的哈，那这章内容可太丰富，感觉作者工作量太大了。

好建议！可能会像一个概述

**Comment by luomai** [comment]
有没有可能按照核心功能来策划章节呢？例如说，

- 概述
- 感知
- 规划
- 控制
- 操作系统：ROS2

**Comment by zsdonghao** [comment]
机器人的系统，和机器学习系统差别还是蛮大的。
目前机器人用到的工具，要么是训练AI用的虚拟环境，如 mujuco, issac gym 这些。
要么就是部署时用的ROS这些。
感觉和机器学习系统差距很大，可能最接近的是MARL类的系统？
