### ISSUE TITLE
chapter_model_deployment: Check image copyright and modify style

### ISSUE THREAD

**Issue by Rudysheeppig** [openmlsys/openmlsys-zh#262]
- For all the pictures in this chapter, check whether the pictures have copyright issues?

- For pictures such as flowcharts, modify the style according to the template. The address of the template is https://github.com/openmlsys/openmlsys-zh/tree/main/info/Pic-Instruction.

**Comment by AssassinGQ** [comment]
模型压缩章节有两张图片要处理

**Comment by AssassinGQ** [comment]
https://github.com/openmlsys/openmlsys-zh/pull/317
https://github.com/openmlsys/openmlsys-zh/pull/287
