### ISSUE TITLE
chapter_reinforcement_learning: Check image copyright and modify style

### ISSUE THREAD

**Issue by Rudysheeppig** [openmlsys/openmlsys-zh#265]
- For all the pictures in this chapter, check whether the pictures have copyright issues?

- For pictures such as flowcharts, modify the style according to the template. The address of the template is https://github.com/openmlsys/openmlsys-zh/tree/main/info/Pic-Instruction.

**Comment by quantumiracle** [comment]
图14.3.3 和14.3.4 是当时这章节reviewer加的，我不知道具体是谁，这两个图应该没有版权，是从别的地方移过来的。看看应该怎么处理。

**Comment by quantumiracle** [comment]
solved in #319
