### ISSUE TITLE
过渡篇内容不应该成为单独章节， 不然会打乱所有章节的顺序

### ISSUE THREAD

**Issue by eedalong** [openmlsys/openmlsys-zh#27]

**Comment by Laicheng0830** [comment]
这块我尝试过解决，用d2lbook貌似不行。
`:maxdepth: 2
:numbered:`
这种方式是设置编号
`:maxdepth: 1`
这种方式是设置不编号，深度为1.
已经在首页的index.md尝试，只能首尾，中间不好插入无编号。
@eedalong 麻烦一起看看有没有解决方法
