### ISSUE TITLE
请问下这里的计算逻辑是否有问题？

### ISSUE THREAD

**Issue by burness** [openmlsys/openmlsys-zh#274]
<img width="668" alt="image" src="https://user-images.githubusercontent.com/3112825/162947128-8f5b9a3c-c64a-42c6-959c-c963385883f7.png">
按我的理解， 这里应该是1024/(200/8) = 40.96？
原文在这儿：https://openmlsys.github.io/chapter_distributed_training/collective.html

**Comment by burness** [comment]
另外在模型部署那块， 混淆模型能否给下引用的资料，比较感兴趣，写了哈

**Comment by luomai** [comment]
@liaopeiyuan 你这一次写带宽计算的时候，fix下这里？

**Comment by luomai** [comment]
@Rudysheeppig 麻烦跟一下模型部署和混淆计算。

**Comment by liaopeiyuan** [comment]
#334 我们在这里fix了这个问题

**Comment by burness** [comment]
点赞
