### ISSUE TITLE
🔥！书籍校验活动获奖名单已公布！

### ISSUE THREAD

**Issue by eedalong** [openmlsys/openmlsys-zh#291]
在下周四（4.28）我们将公布本次书籍校验活动获奖名单以感谢社区用户的参与，敬请期待！

**Comment by Rudysheeppig** [comment]
经过评审，根据大家提交的issue和pr，如下参与书籍众测的同学获得奖项：
forcoder
gian-master
murongmeng
ebagogogo
JieRen98
leeexyz
xlinsist
PuNeal
hansen7
longvoyage
zhanghui-china
maqy1995
hanjr92
HermosaHUI
yuanzhigang-source
Laicheng0830
eedalong

**Comment by gian-master** [comment]
哦吼，中奖咯，啥时候发奖呢？

**Comment by Rudysheeppig** [comment]
获奖可以看看这个贴 https://bbs.huaweicloud.com/forum/thread-186853-1-1.html

**Comment by HermosaHUI** [comment]
咋没联系我呢。刚看到，还中奖了。
