### ISSUE TITLE
附录中的检视问题

### ISSUE THREAD

**Issue by yuanzhigang-source** [openmlsys/openmlsys-zh#298]
图片标识以及引用：
![image](https://user-images.githubusercontent.com/83761884/164921322-cc5204a1-9acc-4db9-8ef5-87943ecbb069.png)

**Comment by yuanzhigang-source** [comment]
![image](https://user-images.githubusercontent.com/83761884/164934183-9107bd07-e08a-41a6-a096-409451dc24f3.png)

**Comment by yuanzhigang-source** [comment]
@eedalong

**Comment by eedalong** [comment]
这个感觉似乎没什么问题
