### ISSUE TITLE
图片制作模板ppt中的中文字体问题

### ISSUE THREAD

**Issue by future-xy** [openmlsys/openmlsys-zh#313]
[书籍图片制作模板](https://github.com/openmlsys/openmlsys-zh/blob/main/info/Pic-Instruction/Requirements%20and%20Instructions.md)要求：

> 插图/插表的标题用小五号黑体，插图/插表的其他文字用小五号字体（中文为宋体，英文为 Time New Roman）

而[模板ppt](https://github.com/openmlsys/openmlsys-zh/blob/main/info/Pic-Instruction/Pic_Templates_and_Samples.pptx)中的中文字体是SimHei（黑体），按照要求似乎应该改为SimSong（宋体）。

**Comment by Rudysheeppig** [comment]
已经修改，提了PR：https://github.com/openmlsys/openmlsys-zh/pull/318
