### ISSUE TITLE
1.3. 机器学习系统基本组成 章节 开始的结构图里面的章节与图书章节不匹配，需要调整

### ISSUE THREAD

**Issue by Rudysheeppig** [openmlsys/openmlsys-zh#333]
![image](https://user-images.githubusercontent.com/17228522/167277921-1f91103b-7273-4834-8058-b9edb4191180.png)

1.3. 机器学习系统基本组成 章节 开始的结构图里面的章节与图书章节不匹配，需要调整。

**Comment by luomai** [comment]
这个已经Fix了。

**Comment by luomai** [comment]
你编译最新的版本就能看到新图。
