### ISSUE TITLE
2.2设计目标    多字导致语句不通顺

### ISSUE THREAD

**Issue by youxiudeshouyeren** [openmlsys/openmlsys-zh#366]
![image](https://user-images.githubusercontent.com/41790911/171990292-1abb79b2-a722-4d17-b9ab-7e4df3c50044.png)
红框所示位置 **机器学习通系统**应为**机器学习系统**

位置在**2.2 设计目标**

**Comment by youxiudeshouyeren** [comment]
@luomai

**Comment by luomai** [comment]
谢谢。你可以直接提交一个PR来修改一下？

**Comment by youxiudeshouyeren** [comment]
> 谢谢。你可以直接提交一个PR来修改一下？

好的 我来修改 感谢你的及时回复
