### ISSUE TITLE
3.2.4. 损失函数和优化器  梯度方向公式有误

### ISSUE THREAD

**Issue by youxiudeshouyeren** [openmlsys/openmlsys-zh#367]
![image](https://user-images.githubusercontent.com/41790911/171991696-f3741db9-24bf-4e9a-884d-9b18f21bf4fd.png)

方向应该仅为梯度，不乘以学习率

位置**3.2.4. 损失函数和优化器**

[@Laicheng0830](https://github.com/Laicheng0830)

**Comment by Laicheng0830** [comment]
@youxiudeshouyeren 对的，感谢指出
