### ISSUE TITLE
CPython -> Cython?

### ISSUE THREAD

**Issue by ziyuang** [openmlsys/openmlsys-zh#41]
https://github.com/openmlsys/openmlsys-zh/blob/main/chapter_programming_interface/c_python_interaction.md
这里的 CPython 是否指 Cython？

**Comment by eedalong** [comment]
@ziyuang 非常感谢你的问题反馈，你是对的，原文拼写错了，我们会在明日的pr中统一更新，如果你有意愿提交pr解决这个问题，我们同样非常的欢迎👏
