### ISSUE TITLE
[编译器前端]图片引用问题

### ISSUE THREAD

**Issue by Laicheng0830** [openmlsys/openmlsys-zh#43]
![image](https://user-images.githubusercontent.com/21324004/157145512-b1cdd8be-8642-4d37-b0ee-794d86f6500f.png)
自动引用无需再加如图，直接如xxx

**Comment by eedalong** [comment]
文献引用不正确

![截屏2022-03-11 下午7 56 10](https://user-images.githubusercontent.com/39682259/157862550-cc724500-7a3a-4af6-9dba-3f5feff61188.png)

**Comment by LiangZhibo** [comment]
图片引用已经全部修改完毕，部分引用格式正确但无法正确显示，暂且遗留。
