### ISSUE TITLE
笔误

### ISSUE THREAD

**Issue by Adnios** [openmlsys/openmlsys-zh#58]
![image](https://user-images.githubusercontent.com/41060790/157622837-27dd9500-f8c8-4824-9027-b096a49888f7.png)
PyTorch 不支持静态图。

**Comment by hanjr92** [comment]
感谢支持，此次描述不够严谨，会对描述进行修改，本意应该是指三个框架都具备即时执行的动态模式，也具备将网络模型序列化固定后交由硬件执行的能力，比如pytorchscript可以将网络模型转换成静态结构。

**Comment by eedalong** [comment]
> 感谢指出，此处描述不够严谨，会对描述进行修改，本意应该是指三个框架都具备即时执行的动态模式，也具备将网络模型序列化固定后交由硬件执行的能力，比如pytorchscript可以将网络模型转换成静态结构。

这样看，说pytorch支持静态图模式执行模式是不是也没有啥太大的问题

**Comment by hanjr92** [comment]
严谨的说，torchscript只是一种转换工具，和完完全全的静态图模式还是有区别的。torchscript更符合后文中静态生成这个概念。

**Comment by eedalong** [comment]
出于纯好奇的讨论，动态图静态图核心区别就是define-and-run和define-by-run的差别，如果用torchscript之类的，也是符合define-and-run这种模式对么。那本质的差别是什么呢？

**Comment by hanjr92** [comment]
我感觉核心区别确实是你说的这个差别，我在文章中也对这两个步骤做了详细的解释，但是我刚在google和百度上搜了一圈，发现之前并没有人提出来pytorch支持静态图 或者static mode这个概念，我们第一个下这个结论是不是不太好 = =！

**Comment by eedalong** [comment]
haha， ok~ @Adnios 给了一个很好的建议哈哈

**Comment by Adnios** [comment]
感谢解释 👍

**Comment by eedalong** [comment]
@hanjr92  please ref this issue in your pr when you fix this issue
