### ISSUE TITLE
[强化学习系统] 章节图片，表格，文献引用显示部分不正确

### ISSUE THREAD

**Issue by eedalong** [openmlsys/openmlsys-zh#59]

**Comment by eedalong** [comment]
<img width="960" alt="截屏2022-03-11 下午4 33 37" src="https://user-images.githubusercontent.com/39682259/157831384-0b5c524d-f1a2-4c5f-9c46-8d1f594acdfc.png">

**Comment by eedalong** [comment]
<img width="963" alt="截屏2022-03-11 下午4 34 10" src="https://user-images.githubusercontent.com/39682259/157831461-23863c54-3fcd-4778-bb70-9c39e5fa081f.png">

**Comment by eedalong** [comment]
<img width="1015" alt="截屏2022-03-11 下午4 34 42" src="https://user-images.githubusercontent.com/39682259/157831530-6b1d2ac8-d8cc-4715-a952-cf83191a794b.png">

**Comment by eedalong** [comment]
<img width="909" alt="截屏2022-03-11 下午4 35 01" src="https://user-images.githubusercontent.com/39682259/157831583-a4e0696a-e70a-479d-961d-fa4d046ee980.png">

**Comment by yuanzhigang-source** [comment]
![aff6dc2f89ce6df6cb6123a0ddf9985c](https://user-images.githubusercontent.com/83761884/158646102-1e97915d-95c1-4075-a1c1-9f8e6994ae63.jpg)

**Comment by quantumiracle** [comment]
已经解决了
