### ISSUE TITLE
第三章 3.3.1表格显示没有居中 

### ISSUE THREAD

**Issue by eedalong** [openmlsys/openmlsys-zh#7]
第三章 3.3.1表格显示没有居中 

![截屏2022-02-25 上午9 08 07](https://user-images.githubusercontent.com/39682259/155634271-a968f4bd-80a9-4ae1-a7bc-695d796c25b7.png)

**Comment by eedalong** [comment]
这个表格的表头和表格内容设置的对齐方式是不是不太一样
![截屏2022-02-25 上午9 09 23](https://user-images.githubusercontent.com/39682259/155634368-5dd8bbb6-4994-45fa-b69e-1a7bc5be9076.png)

**Comment by hanjr92** [comment]
这个居中我试了好久，md里面可以居中，但是html渲染的时候标题就右对齐了，我看李沐他们的网页里面也是这样。

**Comment by eedalong** [comment]
okok, 其实我那一章节也有这个问题
，我也提了issue，还准备今天研究一下看看怎么能解决呢。我估计应该是我们在md里面虽然控制了格式，但是转换成html之后这个格式被忽略了。我看html中的table的align模式是居中，我应该可以写一个自动化脚本来格式化所有的表格显示。

![Uploading 截屏2022-02-25 上午9.50.28.png…]()

**Comment by eedalong** [comment]
Solved @hanjr92
