### ISSUE TITLE
【推荐系统】图片文字问题

### ISSUE THREAD

**Issue by future-xy** [openmlsys/openmlsys-zh#70]

**Comment by eedalong** [comment]
![截屏2022-03-11 下午8 19 51](https://user-images.githubusercontent.com/39682259/157865753-103e9e12-01d9-4dfc-91c1-564ff9ba5903.png)

**Comment by eedalong** [comment]
![截屏2022-03-11 下午8 20 20](https://user-images.githubusercontent.com/39682259/157865819-b551fe99-8d79-4d41-b521-612e8cc3b4be.png)
![截屏2022-03-11 下午8 20 39](https://user-images.githubusercontent.com/39682259/157865876-af4e5d87-2355-40ff-a06a-8510dadb767d.png)

**Comment by future-xy** [comment]
> ![截屏2022-03-11 下午8 20 20](https://user-images.githubusercontent.com/39682259/157865819-b551fe99-8d79-4d41-b521-612e8cc3b4be.png) ![截屏2022-03-11 下午8 20 39](https://user-images.githubusercontent.com/39682259/157865876-af4e5d87-2355-40ff-a06a-8510dadb767d.png)

10.1145/2648584.2648589

It seems the commit is not reflected in your version.

**Comment by eedalong** [comment]
Oh my bad, this is the latest version, 1 minor problem

![截屏2022-03-11 下午9 02 34](https://user-images.githubusercontent.com/39682259/157871525-542bd249-7b1b-4780-8303-57c081f669d4.png)

**Comment by eedalong** [comment]
@future-xy

**Comment by future-xy** [comment]
The latest version #71 should fix them.

**Comment by eedalong** [comment]
please fix conflicts

**Comment by future-xy** [comment]
Merged
