### ISSUE TITLE
联邦学习章节检视意见

### ISSUE THREAD

**Issue by chengtianwu** [openmlsys/openmlsys-zh#85]

**Comment by zhang7-qi** [comment]
章节一：描述联邦学习被提出的背景、解决的问题、引出联邦学习的定义、根据应用场景的样本特征分类（横向、纵向、迁移）、根据部署场景分类（cross-device、cross-silo，并和中心化服务器框架对比）、联邦学习框架的发展、开源平台

**Comment by zhang7-qi** [comment]
章节二：横向联邦学习：分云云联邦（讲一下横向联邦的基础流程+联邦平均算法）、引出端云联邦的四大挑战（系统异构、通信效率、隐私安全、标签缺失），引出我们的分布式FL-Server架构的设计（模块、功能、限时通信模块、集群一致性），端侧框架。

**Comment by zhang7-qi** [comment]
章节三：纵向联邦学习：可以稍微简单一些，纵向联邦架构、纵向联邦流程：PSI数据求交、联邦线性回归半同态加密原理

**Comment by zhang7-qi** [comment]
章节四：联邦学习中的隐私保护技术：pairwise masking，差分隐私、signds

**Comment by zhang7-qi** [comment]
章节五：联邦学习算法的改进：通信效率的提升、智能调频算法、客户端选择、异步联邦。。。

**Comment by TyrQueen** [comment]
图13.3.1 联邦平均算法 权重w的w没有格式

**Comment by chengtianwu** [comment]
> 图13.3.1 联邦平均算法 权重w的w没有格式

好的，多谢建议
