### ISSUE TITLE
检视问题汇总

### ISSUE THREAD

**Issue by missing-9** [openmlsys/openmlsys-zh#87]
【第一章】这里应该是“，”
https://openmlsys.github.io/chapter_introduction/machine_learning_applications.html#id1
![image](https://user-images.githubusercontent.com/29998376/158409879-6e88568f-c2db-4060-9f32-ff1479e15993.png)

**Comment by luomai** [comment]
感谢。对于第一章的修改意见可以在这里统一给出，我会集中修改。

**Comment by maqy1995** [comment]
![image](https://user-images.githubusercontent.com/24785328/158950673-15d2802c-ecbd-4575-886e-a4bae7e8db87.png)
用乎->用户，移动硬件->这里应该是指移动端硬件？

**Comment by luomai** [comment]
@maqy1995 非常感谢。我们支持由贡献者直接提交一个PR来修正这些，也可以我来起PR来改。你希望哪一种？

**Comment by maqy1995** [comment]
> @maqy1995 非常感谢。我们支持由贡献者直接提交一个PR来修正这些，也可以我来起PR来改。你希望哪一种？

虽然我很乐意提交PR，不过这种错别字之类的还是麦老师(@luomai )你这边直接集中修改一下就好了~

**Comment by luomai** [comment]
好，没问题。

**Comment by zhanghui-china** [comment]
比如给定输入图像和它对应的内容标签，则学习图像分类（Classification）。这句话有点怪怪的。
