### ISSUE TITLE
引用图片失败

### ISSUE THREAD

**Issue by yuanzhigang-source** [openmlsys/openmlsys-zh#91]
![aff6dc2f89ce6df6cb6123a0ddf9985c](https://user-images.githubusercontent.com/83761884/158646379-85e73517-c9ba-409a-ae13-3ca034edcfcd.jpg)

**Comment by yuanzhigang-source** [comment]
@eedalong

**Comment by eedalong** [comment]
Great！You are welcomed to fix this issue! @yuanzhigang-source

**Comment by yuanzhigang-source** [comment]
> 

ok,i will propose a pr to solve this problem
