### ISSUE TITLE
【编程接口】检视问题

### ISSUE THREAD

**Issue by TwistsOfFate** [openmlsys/openmlsys-zh#99]
![image](https://user-images.githubusercontent.com/55531508/158945248-51eb94b5-bde3-4149-84de-4cd980fca3b6.png)
“便携” -> “编写”

**Comment by eedalong** [comment]
非常感谢反馈！

**Comment by hanjr92** [comment]
看的真的仔细，很棒！

**Comment by Laicheng0830** [comment]
感谢，已修复
